Add default flow if SMTP data not provided
snoopForms/snoopHub pull request #54
Opened 2022-08-10 15:14 UTC by timothyde

- adds `canSendEmails` function which reads the SMTP config provided
- only send confirmation mail on signup when `canSendEmails` returns true
- conditionally route to verification requested page or to newly added "go to login" page.

Probably could also leave out the login step, but I felt like this is the better UX :)

2022-08-11 12:43 UTC, matthiasnannt requested changes
@timothyde nice work! Works, looks great and has zero build errors 😅💪

There are only two things that bother me and I think could be improved:
- Because we are planning to use smtp settings for more feature in snoopHub and I think having a dedicated env variable to enable/disable email verification would be nice
- You now set the user attribute `emailVerified` to the current date when email verification is enabled. I would prefer if you leave it blank and skip the verification check on login instead because the email address isn't verified for this user and if you in some cases want to ensure emails are verified at a later point and enable email verification you don't know which emails are verified and which are not.

It would be great if you could change these two things. but great work so far 💪

2022-08-11 19:33 UTC, timothyde commented
Yeah, good points, I revamped it using an explicit env variable :)

2022-08-12 12:17 UTC, matthiasnannt commented
thanks for the changes @timothyde 💪 looks great and worked well in my tests.

I just thought about one thing that could be a problem for some users. Disabling verification will be the default setting also in `.env.example` , e.g.
```EMAIL_VERIFICATION_DISABLED=1```

But if a user then wants to enable email verification, currently the only option would be to delete the env variable to make the checks in the code work, because it only checks if the value (which is always a string in env variables) would be interpreted as true (which is always the case for every non empty string).
`EMAIL_VERIFICATION_DISABLED=0` would still not enable verification.

So I think we should take care that 0 means false and 1 means true. Easiest point would be to do that in next.config.js where we load the env variable but I don't know if it's good practice to do so. What do you think?

2022-08-12 12:45 UTC, timothyde commented
I didn't even know that an env value of 0 would be truthy in JS ;) A quick search showed that the 0/1 values in .env files are the way to go, assumed it would be falsy and didn't check it. Googled it again and it seems like checking for strict quality via `=== '1'` is the suggested way. I now did that in `next.config.js` and feel like it's as good a place as any :)

2022-08-14 09:10 UTC, matthiasnannt approved these changes
works great now! 🎉 thanks a lot for this PR. This makes trying self-hosted snoopForms way easier!

2022-08-14 09:11 UTC, merged